version: '3.5'

services:
  ebaby-api:
    build: ./
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - ebaby
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - ebaby

networks:
  ebaby:

volumes:
  mongo:
